spring:
  application:
    name: double-bean-api-server

  devtools:
    restart:
      enabled: true
      additional-exclude: static/**, public/**
    livereload:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/double_bean?allowMultiQueries=true
    username: root
    password: ssafy

auth:
  jwt:
    secretKey: axbcshbrAFkufvkdfusvdKDS387rslsdf87gwegodscuSDF983iusg8WaFSD83

openapi:
  service-key: rf2THTSq3Rnvz7yUJWlRW2YjsfVvxufJssCC4SgBAcoGXoIE/fZH72XMDiy4AYxbmYQXRGYxAFKO1+AKnL91rg==

